[package]
name = "Tamriel_Data"
version = "10.1"
description = "The data repository for Tamriel Rebuilt, Project Tamriel and Padomic Isles province mods."
homepage = "https://www.nexusmods.com/morrowind/mods/44537"
repository = "https://github.com/TD-Addon/TD_Addon"
authors = [
	"chef",
	"Kynesifnar",
	"Evil Eye",
	"Alyst3r",
	"Jackimoff Wackimoff",
	"Rats",
	"Melchior Dahrk",
	"Dillon",
	"MwGek",
	"SACarrow",
]

[dependencies.mwse]
buildnumber = 3074

[tools.csse]
deprecated = [
	"T_De_ToyGuar_01",
	"T_De_SetRed_X_Skar_01",
	"T_De_BonemoldKragen_Helm_01",
	"T_Com_SetHarbor_FishBeheaded_01",
	"T_Com_SetHarbor_FishBeheaded_02",
	"TR_hla_canyon_guard",
	"TR_hla_canyon_guard_f",
	"TR_hla_canyon_guard_f_s",
	"TR_hla_canyon_guard_s",
	"TR_hla_canyon_shooter",
	"TR_hla_guard",
	"TR_hla_guard_f",
	"TR_hla_guard_s",
	"TR_hla_kragen_guard",
	"TR_hla_kragen_guard_f",
	"TR_hla_kragen_guard_f_s",
	"TR_hla_kragen_guard_s",
	"TR_hla_kragen_shooter",
	"TR_hla_sharpshooter",
	"TR_imp_archer",
	"TR_imp_archer_b",
	"TR_imp_archer_s",
	"TR_imp_guard",
	"TR_imp_guard_cap",
	"TR_imp_guard_cap_s",
	"TR_imp_guard_s",
	"TR_ind_guard",
	"TR_ind_guard_f",
	"TR_ind_guard_f_s",
	"TR_ind_guard_s",
	"TR_ind_ulvra_guard",
	"TR_ind_ulvra_guard_f",
	"TR_ind_ulvra_guard_f_s",
	"TR_ind_ulvra_guard_s",
	"TR_ordinator",
	"TR_ordinator_high",
	"TR_ordinator_high_s",
	"TR_ordinator_s",
	"TR_ordinator_war",
	"TR_ordinator_war_s",
	"TR_red_guard",
	"TR_red_guard_b",
	"TR_red_guard_f",
	"TR_red_guard_f_s",
	"TR_red_guard_s",
	"TR_red_guard_strong",
	"TR_red_guard_strong_f",
	"TR_red_stone_guard",
	"TR_red_stone_guard_f",
	"TR_red_stone_guard_f_s",
	"TR_red_stone_guard_s",
	"TR_red_watchman",
	"TR_red_watchman_b",
	"TR_red_watchman_f",
	"TR_red_watchman_s",
	"TR_telv_guard",
	"TR_telv_guard_s",
	"TR_telvanni guard_02",
	"TR_telvanni guard_02_s",
	"T_Mw_Flora_RedCoral01",
	"T_Mw_Flora_RedCoral02",
	"T_Mw_Flora_RedCoral03",
	"T_De_ToyGuar_01",
	"T_Tsa_F_Urn_01",
	"T_Tsa_F_Urn_02",
	"T_Yne_Drink_Pudjing",
	"T_Pi_FloraYn_FlowerY_01",
	"T_Pi_FloraYn_FlowerY_02",
	"T_Pi_FloraYn_FlowerY_03",
	"T_Mw_FloraCM_Maiden03",
	"T_Mw_FloraCM_Maiden04",
	"T_Mw_FloraCM_Maiden05",
	"T_Mw_FloraCM_Maiden06",
	"T_Mw_Fau_Eyest_01",
	"T_Mw_Fau_EyestDs_01",
	"T_Mw_Fauna_Riverstrider_01",
	"T_Com_SetCyr_SignWayBrenaFt_01",
	"T_Com_SetCyr_SignWayBrenaFt_02",
	"T_Com_SetCyr_SignWayFtIstiru_01",
	"T_Com_SetCyr_SignWayFtOntus_03",
	"T_Com_SetCyr_SignWayFtStrand_01",
	"T_Com_SetCyr_SignWayHastrel_03",
	"T_Com_SetCyr_SignWayHastrel_04",
	"T_Com_SetCyr_SignWayWariel_03",
	"T_Com_SetCyr_SignWayWariel_04",
	"T_Note_WayrestJewelOfTheBayTR",
	"T_Imp_Newtscale_Cuirass_01",
	"T_Gob_Goblin_Arrow_01",
	"T_Orc_UngorthBottle_01",
	"T_Com_SetMw_SignWaySaintSery_01",
	"T_Com_SetMw_SignWaySaintSery_02",
	"T_Com_SetMw_SignWaySeryn_01",
	"T_Mw_FloraOW_Cupling01",
	"T_Mw_FloraOW_Cupling02",
	"T_Mw_FloraOW_Cupling03",
	"T_Mw_FloraOW_Cupling04",
	"T_Mw_FloraOW_Cupling05",
	"T_Mw_FloraOW_Cupling06",
	"T_HF_Fau_Mastreeve_01",
	"T_Po_Fauna_Coral01_01",
	"T_Po_Fauna_Coral01_02",
	"T_Po_Fauna_Coral01_03",
	"T_Po_Fauna_Coral01_04",
	"T_Po_Fauna_Coral01_05",
	"T_Po_Fauna_Coral01_06",
	"T_Po_Fauna_Coral01_07",
	"T_Po_Fauna_Coral01_08",
	"T_Po_Fauna_Coral01_09",
	"T_Po_Fauna_Coral02_01",
	"T_Po_Fauna_Coral02_02",
	"T_Po_Fauna_Coral02_03",
	"T_Po_Fauna_Coral02_04",
	"T_Po_Fauna_Coral02_05",
	"T_Po_Fauna_Coral02_06",
	"T_Po_Fauna_Coral02_07",
	"T_Po_Fauna_Coral02_08",
	"T_Po_Fauna_Coral02_09",
	"T_Po_Fauna_Coral02_10",
	"T_Po_Fauna_Coral03_01",
	"T_Po_Fauna_Coral03_02",
	"T_Po_Fauna_Coral03_03",
	"T_Po_Fauna_Coral03_04",
	"T_Po_Fauna_CoralGrp02_01",
	"T_Po_Fauna_CoralGrp02_02",
	"T_Po_Fauna_CoralGrp02_03",
	"T_Po_Fauna_CoralGrp02_04",
	"T_Mw_CaveSH_Hall_34",
	"T_Mw_CaveSH_Hall_11",
	"T_Mw_CaveSH_R_Sid_04",
	"T_Mw_CaveSH_R_Cor_06",
	"T_Mw_CaveSH_RockB_06",
	"T_Mw_CaveSH_RockB_07",
	"T_Mw_CaveSH_RockB_08",
	"T_IngCrea _GremlinEarWax_01",
	"T_IngCrea _SnowraySting_01",
	"T_Kha _Furn_Tapestry_01",
	"T_Kha _Furn_Tapestry_02",
	"T_QyK_FurnP_Chest",
	"T_QyK_FurnP_ChestS",
	"T_Yne_FurnM_Chest_01",
	"T_Yne_FurnM_Chests_01",
	"T_C_ComCmShirt01_FaF",
	"T_C_ComCmShirt01_UAF",
	"T_C_ComCmShirt01_WF",
	"T_C_ComCmShirt02_FaF",
	"T_C_ComCmShirt02_UAF",
	"T_C_ComCmShirt02_WF",
	"T_C_ComCmShirt03_UAF",
	"T_C_ComCmShirt04_UAF",
	"T_C_ComEpShirt03_FaF",
	"T_C_ComEpShirt03_UAF",
	"T_C_ComEpShirt03_WF",
	"T_Nor_UNI_ShardOfVehemence",
	"T_Nor_UNI_NebsTalon",
	"T_Hr_CaveGT_I_4way_Room_01",
	"T_Hr_CaveLS_I_4way_Room_01",
	"T_Hr_CaveMU_I_4way_Room_01",
	"T_Pi_FloraTM_Succulant",
	"T_ChQ_Tm_Statue_UNI",
	"T_Mw_TerrChlorineDS_Mist01",
	"T_Mw_TerrChlorineDS_Mist02",
	"T_Mw_TerrChlorineDS_Pool1024_01",
	"T_Mw_TerrChlorineDS_Pool256_01",
	"T_Mw_TerrChlorineDS_Pool512_01",
	"T_Nor_SetHarbor_BoatFisher_01",
	"T_Nor_SetHarbor_BoatFisher_02",
	"T_Nor_SetHarbor_BoatFisherSt_01",
	"T_Nor_SetHarbor_BoatFisherSt_02",
	"T_De_RedWatchChitin_Boots_01",
	"T_De_RedWatchChitin_Cuirass_01",
	"T_De_RedWatchChitin_GauntlL_01",
	"T_De_RedWatchChitin_GauntlR_01",
	"T_De_RedWatchChitin_Greaves_01",
	"T_De_RedWatchChitin_PauldrL_01",
	"T_De_RedWatchChitin_PauldrR_01",
	"T_Imp_Dragonscale_cuirass_01",
	"T_Imp_Dragonscale_helm_01",
	"T_A_DeBonemoldKragenHelm01_Hd",
	"T_B_He_UNI_HeadEldaleTR",
	"T_CathKep_Furn_Urn_01",
	"T_CathKep_Furn_Urn_02",
	"T_CathKep_Furn_Urn_03",
	"T_Cnq_Flora_DriftPuf_01",
	"T_Cnq_Flora_DriftPuf_02",
	"T_Cnq_Flora_DriftPuf_03",
	"T_Cnq_Flora_DriftPuf_04",
	"T_Cnq_Flora_DriftPuf_05",
	"T_Mw_FloraDS_SStrap01",
	"T_Mw_FloraDS_SStrap02",
	"T_De_SetOM_Door_Round",
	"T_De_SetOM_Door_Square",
	"T_IngFood_BreadDeshaan_01",
	"T_IngFood_BreadDeshaan_02",
	"T_IngFood_BreadDeshaan_03",
	"T_IngFood_BreadDeshaan_04",
	"T_IngFood_BreadDeshaan_05",
	"T_Dae_Regular_Scimitar_02",
	"T_De_Aena_Arrow_01",
	"T_De_Aena_Sickle_01",
	"T_De_Aena_Spear_01",
	"T_De_UNI_EthosKnife",
	"T_De_UNI_TreasureWoodSword",
	"T_Nor_Var_WerewolfboneDagger_01",
	"T_De_SetDres_X_B_Floor_256",
	"T_De_SetDres_X_B_L_3way_01",
	"T_De_SetDres_X_B_L_3way_02",
	"T_De_SetDres_X_B_L_3way_03",
	"T_De_SetDres_X_B_L_Cnr_01",
	"T_De_SetDres_X_B_L_Cnr_02",
	"T_De_SetDres_X_B_L_Cnr_03",
	"T_De_SetDres_X_B_L_Cnr_04",
	"T_De_SetDres_X_B_L_Pil_Cnr",
	"T_De_SetDres_X_B_L_Pil_Str",
	"T_De_SetDres_X_B_L_Ramp_01",
	"T_De_SetDres_X_B_L_Ramp_02",
	"T_De_SetDres_X_B_L_Ramp_03",
	"T_De_SetDres_X_B_L_Ramp_04",
	"T_De_SetDres_X_B_L_Ramp_10",
	"T_De_SetDres_X_B_L_Ramp_11",
	"T_De_SetDres_X_B_L_Ramp_12",
	"T_De_SetDres_X_B_L_Str_01",
	"T_De_SetDres_X_B_L_Str_011",
	"T_De_SetDres_X_B_L_Str_012",
	"T_De_SetDres_X_B_L_Str_013",
	"T_De_SetDres_X_B_M_3way_01",
	"T_De_SetDres_X_B_M_3way_02",
	"T_De_SetDres_X_B_M_3way_03",
	"T_De_SetDres_X_B_M_Cnr_01",
	"T_De_SetDres_X_B_M_Cnr_02",
	"T_De_SetDres_X_B_M_Cnr_03",
	"T_De_SetDres_X_B_M_Cnr_04",
	"T_De_SetDres_X_B_M_Pil_Cnr",
	"T_De_SetDres_X_B_M_Pil_Str",
	"T_De_SetDres_X_B_M_Str_01",
	"T_De_SetDres_X_B_M_Str_011",
	"T_De_SetDres_X_B_M_Str_012",
	"T_De_SetDres_X_B_M_Str_013",
	"T_De_SetDres_X_B_T_Cnr_01",
	"T_De_SetDres_X_B_T_Cnr_02",
	"T_De_SetDres_X_B_T_Cnr_03",
	"T_De_SetDres_X_B_T_Cnr_04",
	"T_De_SetDres_X_B_T_Pil_Cnr",
	"T_De_SetDres_X_B_T_Pil_Str",
	"T_De_SetDres_X_B_T_Str_01",
	"T_De_SetInd_I_Ceiling_01",
	"T_De_SetInd_I_Entrance_01",
	"T_De_SetInd_I_Entrance_02",
	"T_De_SetInd_I_EntranceCorner_01",
	"T_De_SetInd_I_Floor_01",
	"T_De_SetInd_I_FloorMetal_01",
	"T_De_SetInd_I_Planter_01",
	"T_De_SetInd_I_Planter_02",
	"T_De_SetInd_I_Planter_03",
	"T_De_SetInd_I_Railing_01",
	"T_De_SetInd_I_Stairs_01",
	"T_De_SetInd_I_Wall_01",
	"T_De_SetInd_I_Wall_02",
	"T_De_SetInd_I_Wall_OneSided_01",
	"T_De_SetInd_I_WallMetal_01",
	"T_De_SetInd_X_Aquaduct_01",
	"T_De_SetInd_X_AquaductEnd_01",
	"T_De_SetInd_X_AquaductEnd_02",
	"T_De_SetInd_X_Awning_01",
	"T_De_SetInd_X_Balcony_01",
	"T_De_SetInd_X_Bridge_01",
	"T_De_SetInd_X_Bridge_02",
	"T_De_SetInd_X_Bridge_03",
	"T_De_SetInd_X_Bridge_04",
	"T_De_SetInd_X_Bridge_05",
	"T_De_SetInd_X_Bridge_06",
	"T_De_SetInd_X_Bridge_07",
	"T_De_SetInd_X_BridgeEnd_01",
	"T_De_SetInd_X_BridgeEnd_02",
	"T_De_SetInd_X_BridgeSection_01",
	"T_De_SetInd_X_BridgeStair_01",
	"T_De_SetInd_X_BridgeStair_02",
	"T_De_SetInd_X_Buttress_01",
	"T_De_SetInd_X_Column_01",
	"T_De_SetInd_X_Dock_01",
	"T_De_SetInd_X_Dock_02",
	"T_De_SetInd_X_Dock_03",
	"T_De_SetInd_X_Dock_04",
	"T_De_SetInd_X_Dock_05",
	"T_De_SetInd_X_Dock_End",
	"T_De_SetInd_X_Dock_PlatformL",
	"T_De_SetInd_X_Dock_PlatformR",
	"T_De_SetInd_X_Dock_Ramp",
	"T_De_SetInd_X_Dock_Straight",
	"T_De_SetInd_X_Dome_01",
	"T_De_SetInd_X_DWall_01",
	"T_De_SetInd_X_Fence_01",
	"T_De_SetInd_X_Ground_01",
	"T_De_SetInd_X_Ground_02",
	"T_De_SetInd_X_Ground_03",
	"T_De_SetInd_X_Ground_04",
	"T_De_SetInd_X_HWall_01",
	"T_De_SetInd_X_HWall_02",
	"T_De_SetInd_X_HWall_03",
	"T_De_SetInd_X_HWall_04",
	"T_De_SetInd_X_HWStair_01",
	"T_De_SetInd_X_Manor_01",
	"T_De_SetInd_X_Monolith_01",
	"T_De_SetInd_X_Pagoda_01",
	"T_De_SetInd_X_Pagoda_02",
	"T_De_SetInd_X_Path_3Way_01",
	"T_De_SetInd_X_Path_3Way_02",
	"T_De_SetInd_X_Path_4Way_01",
	"T_De_SetInd_X_Path_Cnr_01",
	"T_De_SetInd_X_Path_Cnr_02",
	"T_De_SetInd_X_Path_Cnr_03",
	"T_De_SetInd_X_Path_Cnr_04",
	"T_De_SetInd_X_Path_Cur_01",
	"T_De_SetInd_X_Path_Cur_02",
	"T_De_SetInd_X_Path_Cur_03",
	"T_De_SetInd_X_Path_Cur_04",
	"T_De_SetInd_X_Path_End_01",
	"T_De_SetInd_X_Path_Step_01",
	"T_De_SetInd_X_Path_Step_02",
	"T_De_SetInd_X_Path_Step_03",
	"T_De_SetInd_X_Path_Step_04",
	"T_De_SetInd_X_Path_Str_01",
	"T_De_SetInd_X_Path_Str_02",
	"T_De_SetInd_X_Pavillion_01",
	"T_De_SetInd_X_PavillionGate_01",
	"T_De_SetInd_X_PavillionTower_01",
	"T_De_SetInd_X_PavillionWall_02",
	"T_De_SetInd_X_Pier_01",
	"T_De_SetInd_X_Pier_02",
	"T_De_SetInd_X_Pier_03",
	"T_De_SetInd_X_Pillar_01",
	"T_De_SetInd_X_Pillar_02",
	"T_De_SetInd_X_Planter_01",
	"T_De_SetInd_X_Platform_01",
	"T_De_SetInd_X_Platform_02",
	"T_De_SetInd_X_Platform_03",
	"T_De_SetInd_X_Platform_04",
	"T_De_SetInd_X_Platform_05",
	"T_De_SetInd_X_Platform_06",
	"T_De_SetInd_X_Roadmarker_01",
	"T_De_SetInd_X_Rubble_01",
	"T_De_SetInd_X_Shed_01",
	"T_De_SetInd_X_SmallWall_01",
	"T_De_SetInd_X_SmallWall_02",
	"T_De_SetInd_X_SmallWall_03",
	"T_De_SetInd_X_SmallWall_04",
	"T_De_SetInd_X_SmallWall_05",
	"T_De_SetInd_X_Stair_01",
	"T_De_SetInd_X_Stair_02",
	"T_De_SetInd_X_Stair_03",
	"T_De_SetInd_X_Stair_04",
	"T_De_SetInd_X_Stair_05",
	"T_De_SetInd_X_Stair_06",
	"T_De_SetInd_X_StriderPort_01",
	"T_De_SetInd_X_Tower_01",
	"T_De_SetInd_X_Tower_02",
	"T_De_SetInd_X_Tower_03",
	"T_De_SetInd_X_Tower_04",
	"T_De_SetInd_X_Tower_05",
	"T_De_SetInd_X_Tower_06",
	"T_De_SetInd_X_Tower_07",
	"T_De_SetInd_X_Tower_08",
	"T_De_SetInd_X_TowerWindow_01",
	"T_De_SetInd_X_Wall_01",
	"T_De_SetInd_X_Wall_01b",
	"T_De_SetInd_X_Wall_01c",
	"T_De_SetInd_X_Wall_02",
	"T_De_SetInd_X_Wall_03",
	"T_De_SetInd_X_WaterSpray_01",
	"T_De_SetOM_X_Building_01",
	"T_De_SetOM_X_Building_02",
	"T_De_SetOM_X_Building_03",
	"T_De_SetOM_X_Building_04",
	"T_De_SetOM_X_Building_05",
	"T_De_SetOM_X_Building_06",
	"T_De_SetOM_X_Building_07",
	"T_De_SetOM_X_Building_08",
	"T_De_SetOM_X_Building_09",
	"T_De_SetOM_X_Building_10",
	"T_De_SetOM_X_Building_11",
	"T_De_SetOM_X_Building_12",
	"T_De_SetOM_X_Building_13",
	"T_De_SetOM_X_Building_14",
	"T_De_SetOM_X_Building_D_01",
	"T_De_SetOM_X_Building_D_02",
	"T_De_SetOM_X_Building_D_03",
	"T_De_SetOM_X_Building_D_04",
	"T_De_SetOM_X_Building_S_01",
	"T_De_SetOM_X_Building_S_02",
	"T_De_SetOM_X_Building_S_03",
	"T_De_SetOM_X_Chapel_01",
	"T_De_SetOM_X_Doorway_01",
	"T_De_SetOM_X_Doorway_02",
	"T_De_SetOM_X_Platform_S_01",
	"T_De_SetOM_X_Platform_S_02",
	"T_De_SetOM_X_Platform_S_03",
	"T_De_SetOM_X_Platform_S_04",
	"T_De_SetOM_X_Platform_S_05",
	"T_De_SetOM_X_Platform_S_06",
	"T_De_SetOM_X_Platform_S_07",
	"T_De_SetOM_X_Platform_S_08",
	"T_De_SetOM_X_Platform_S_09",
	"T_De_SetOM_X_Platform_S_10",
	"T_De_SetOM_X_Platform_S_11",
	"T_De_SetOM_X_Platform_S_12",
	"T_De_SetOM_X_Platform_S_13",
	"T_De_SetOM_X_Platform_S_14",
	"T_De_SetOM_X_Platform_S_15",
	"T_De_SetOM_X_Platform_S_16",
	"T_De_SetOM_X_Platform_S_17",
	"T_De_SetOM_X_Platform_S_end",
	"T_De_SetOM_X_Wall_S_00",
	"T_De_SetOM_X_Wall_S_01",
	"T_De_SetOM_X_Wall_S_02",
	"T_De_SetOM_X_Wall_S_03",
	"T_De_SetOM_X_Wall_S_04",
	"T_De_SetOM_X_Wall_S_05",
	"T_De_SetOM_X_Wall_S_06",
	"T_De_SetOM_X_Wall_S_07",
	"T_De_SetOM_X_Wall_S_08",
	"T_De_SetOM_X_Wall_S_09",
	"T_De_SetOM_X_Wall_S_10",
	"T_De_SetOM_X_Wall_S_11",
	"T_De_SetOM_X_Wall_S_12",
	"T_De_SetOM_X_Wall_S_13",
	"T_De_SetOM_X_Wall_S_14",
	"T_De_SetOM_X_Wall_S_P",
	"T_De_SetOM_X_Well",
	"T_De_SetOM_X_Window_02",
	"T_De_SetOM_X_Window_03",
	"T_De_SetOM_X_Window_04",
	"T_Dae_Regular_Scimitar_02",
	"T_De_Aena_Arrow_01",
	"T_De_Aena_Sickle_01",
	"T_De_Aena_Spear_01",
	"T_De_UNI_EthosKnife",
	"T_De_UNI_TreasureWoodSword",
	"T_Nor_Var_WerewolfboneDagger_01",
	"T_MwCom_Var_Bl1ArrowAena",
]